### PR TITLE
Update sdk to 3.36

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build

**Comment by LeandroStanger** [comment]
bot, build net.lutris.Lutris.Runner.Wine

**Comment by AsciiWolf** [comment]
Looks good. @gasinvein @LeandroStanger Is there anything preventing this from being merged? (Also, the old PRs should probably be closed.)

**Comment by gasinvein** [comment]
@AsciiWolf I'm afraid this repo is left without a maintainer. Now only flathub admins have push permissions to it.

**Comment by AsciiWolf** [comment]
@gasinvein Ah, that is a really bad news. :-/

/cc @bilelmoussaoui

**Comment by bilelmoussaoui** [comment]
Anyone wants to take over the maintenance of this repository? Will merge once the build pass

**Comment by AsciiWolf** [comment]
I already have too many Flatpaks and other things to maintain/work on. :-(

**Comment by gasinvein** [comment]
@AsciiWolf I've fixed the build locally, tried it, and looks like lutris wine 5.5 is broken anyway. 5.4 works fine.

**Pull request closed without merging**
